### Маметкадыров Ынтымак, НПМбд-02-20

## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


In [4]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [133]:
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [116]:
n = 10
a = np.arange(1, 4)
np.tile(a, 3*n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,
       1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [118]:
np.arange(1, 21, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [61]:
zeros = np.zeros((10, 10))
zeros[0] = 1
zeros[-1] = 1
zeros[1:-1, 0] = 1
zeros[1:-1, -1] = 1
zeros

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [74]:
np.eye(8, 8, -6) + np.eye(8, 8, -4) + np.eye(8, 8, -2) + np.eye(8) + np.eye(8, 8, 2) + np.eye(8, 8, 4) + np.eye(8, 8, 6)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [128]:
def create_matrix(n):
    A = np.ones((n, n))
    for i in range (n):
        for j in range(n):
            A[i, j] = i + j
    return A

In [130]:
create_matrix(10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [11]:
# вектор на вектор
a = np.arange(1, 10)
b = np.ones(9)
a.dot(b)

45.0

In [55]:
# матрица на вектор
a = np.random.rand(3, 3)
b = np.array([1, 2, 3])
a.dot(b)

array([3.10818406, 3.35912129, 3.60121022])

In [58]:
# матрица на матрицу
a = np.random.rand(5, 4)
b = np.random.rand(4, 2)
a.dot(b)

array([[1.73999717, 1.1060597 ],
       [2.1663422 , 1.27751416],
       [1.38613305, 0.87161284],
       [0.74217766, 0.4302802 ],
       [1.57158301, 1.06111613]])

8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [138]:
cos_values = np.cos(np.arange(0, 1.05, 0.05))
sin_values = np.sin(np.arange(0, 1.05, 0.05))
np.concatenate((cos_values, sin_values))

array([1.        , 0.99875026, 0.99500417, 0.98877108, 0.98006658,
       0.96891242, 0.95533649, 0.93937271, 0.92106099, 0.9004471 ,
       0.87758256, 0.85252452, 0.82533561, 0.7960838 , 0.76484219,
       0.73168887, 0.69670671, 0.65998315, 0.62160997, 0.58168309,
       0.54030231, 0.        , 0.04997917, 0.09983342, 0.14943813,
       0.19866933, 0.24740396, 0.29552021, 0.34289781, 0.38941834,
       0.43496553, 0.47942554, 0.52268723, 0.56464247, 0.60518641,
       0.64421769, 0.68163876, 0.71735609, 0.75128041, 0.78332691,
       0.8134155 , 0.84147098])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [150]:
A = np.random.uniform(-1, 3, (3, 5))
A

array([[-0.94091857,  1.63659264,  2.60781384,  1.53421126,  1.2895366 ],
       [ 1.29178878,  0.22467208,  0.11509901,  0.21533279,  2.82102124],
       [-0.34423694, -0.14327153,  1.94734359,  1.36734152,  1.95264334]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [151]:
A.sum()

15.574969653660276

In [152]:
A.sum(axis=1)

array([6.12723578, 4.6679139 , 4.77981998])

In [153]:
A.sum(axis=0)

array([0.00663328, 1.71799319, 4.67025645, 3.11688557, 6.06320117])

In [154]:
A.mean(axis=1)

array([1.22544716, 0.93358278, 0.955964  ])

In [155]:
A.var(axis=1)

array([1.37451229, 1.07581772, 1.00885518])

In [156]:
A.std(axis=1)

array([1.17239596, 1.03721633, 1.00441783])

11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [157]:
A

array([[-0.94091857,  1.63659264,  2.60781384,  1.53421126,  1.2895366 ],
       [ 1.29178878,  0.22467208,  0.11509901,  0.21533279,  2.82102124],
       [-0.34423694, -0.14327153,  1.94734359,  1.36734152,  1.95264334]])

In [164]:
A = A - (A.mean(axis=1)/A.std(axis=1)).reshape(3, 1)
A

array([[-2.13986851,  0.43764269,  1.4088639 ,  0.33526132,  0.09058665],
       [ 0.35940794, -0.70770876, -0.81728183, -0.71704806,  1.88864039],
       [-1.30018244, -1.09921704,  0.99139809,  0.41139602,  0.99669784]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [166]:
ind = np.argsort(A, axis=0)
ind[:, :-1] = ind[:, -1].reshape(3, 1)
np.take_along_axis(A, ind, axis=0)

array([[-2.13986851,  0.43764269,  1.4088639 ,  0.33526132,  0.09058665],
       [-1.30018244, -1.09921704,  0.99139809,  0.41139602,  0.99669784],
       [ 0.35940794, -0.70770876, -0.81728183, -0.71704806,  1.88864039]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [167]:
B = A.T.dot(A)
B

array([[ 6.3986857 ,  0.23832872, -4.59751946, -1.51001778, -0.8109402 ],
       [ 0.23832872,  1.90066091,  0.10521483,  0.20197235, -2.39255001],
       [-4.59751946,  0.10521483,  3.63571725,  1.46622514, -0.42780288],
       [-1.51001778,  0.20197235,  1.46622514,  0.79580475, -0.91383821],
       [-0.8109402 , -2.39255001, -0.42780288, -0.91383821,  4.56857505]])

In [168]:
C = A.dot(A.T)
C

array([[ 6.87607196, -2.29956103,  3.92611283],
       [-2.29956103,  5.3790958 ,  1.08779107],
       [ 3.92611283,  1.08779107,  5.04427589]])

Можно сказать, что произведение матриц не обладает свойством коммутативности, т. е. от перестановки мест произведение меняется.  
В первом случае мы умножаем матрицу имеющий размер (5х3) на матрицу размерности (3х5), в результате получили матрицу с размером (5х5).  
Во-втором случае матрицу размерностью (3х5) умножили на матрицу размерности (5х3), получили матрицу с размером (3х3).  
Отличие заключается в том, что в первом случае мы сначала транспонируем матрицу, затем умножаем на исходную матрицу А. Во-втором случае исходную матрицу умножаем на транспонированную матрицу.

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [169]:
B.diagonal().sum()

17.299443654672004

In [170]:
C.diagonal().sum()

17.299443654672004

15. Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg).

In [171]:
# нельзя найти определитель матрицы А, т. к. она не квадратная.
np.linalg.det(A)

LinAlgError: Last 2 dimensions of the array must be square

In [172]:
# ранг матрицы А
np.linalg.matrix_rank(A)

3

In [176]:
# определитель матрицы В
np.linalg.det(B)

-1.1911009832072855e-30

In [180]:
# ранг матрицы В
np.linalg.matrix_rank(B)

3

In [178]:
# определитель матрицы C
np.linalg.det(C)

49.2052496102993

In [179]:
# ранг матрицы C
np.linalg.matrix_rank(C)

3

In [181]:
# собственные значения матрицы B
np.linalg.eig(B)

(array([ 1.02871040e+01, -1.25754704e-15,  7.65726539e-01,  6.24661314e+00,
         0.00000000e+00]),
 array([[ 0.7825247 ,  0.54693536,  0.28764934, -0.07599121, -0.06706402],
        [ 0.02210013,  0.30309329, -0.76366198, -0.48164154,  0.26465863],
        [-0.58409847,  0.70639207,  0.21397186, -0.12069583, -0.39965295],
        [-0.21012312,  0.03777144,  0.45453513, -0.17135228,  0.83659129],
        [-0.04294092,  0.3295144 , -0.2858183 ,  0.84753624,  0.25661404]]))

In [182]:
# собственные значения матрицы C
np.linalg.eig(C)

(array([ 0.76572654, 10.28710398,  6.24661314]),
 array([[-0.59629061, -0.79881461, -0.07957837],
        [-0.45342492,  0.25333881,  0.8545322 ],
        [ 0.66245252, -0.54563235,  0.51326601]]))

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [335]:
np.random.seed(1032201730)
np.random.randint(9)

2

In [190]:
analytical_solution_2 = (np.e - np.power(np.e, 1/4))/2
analytical_solution_2

0.7171282058856518

In [183]:
analytical_solution_9 = (np.pi * np.sqrt(2))/4
analytical_solution_9

1.1107207345395915

In [20]:
def integral(x):
    return (np.power(np.e, 1/np.power(x, 2)))/np.power(x, 3)

In [19]:
def integral_9(x):
    return 1/np.sqrt(2 + 3*x - 2*np.power(x, 2))

In [18]:
def solve_integral(start, end, step, method, integral_number):
    if integral_number == 2:
        xr = np.arange(start, end+step, step)
        yr = integral(xr)
    elif integral_number == 9:
        xr = np.arange(start, end, step)
        yr = integral_9(xr)
    if method == 'rectangle':
        answer = step * yr.sum()
        return answer
    elif method == 'trapezoid':
        answer = (step/2)*(yr[0] + 2*yr[1:-1].sum() + yr[-1])
        return answer
    elif method == 'Simpson':
        answer = (step/3) * (yr[0] + 2 * yr[2:len(xr) - 1:2].sum() + 4 * yr[1:len(xr) - 1:2].sum() + yr[-1])
        return answer

In [188]:
rectangle_method = solve_integral(1, 2, 0.00001, 'rectangle', 2)
rectangle_method

0.7171425999179541

In [191]:
rectangle_method - analytical_solution_2

1.439403230230063e-05

In [193]:
trapezoid_method = solve_integral(1, 2, 0.0001, 'trapezoid', 2)
trapezoid_method

0.717144265891294

In [194]:
trapezoid_method - analytical_solution_2

1.606000564213783e-05

In [200]:
Simpson_method = solve_integral(1, 2, 0.01, 'Simpson', 2)
Simpson_method

0.7171282495037867

In [201]:
Simpson_method - analytical_solution_2

4.3618134881739934e-08

In [476]:
rectangle_method_9 = solve_integral(3/4, 1.9, 0.001, 'rectangle', 9)+solve_integral(1.899, 1.99, 0.000001, 'rectangle', 9)+solve_integral(1.989999, 1.9999989, 0.0000001, 'rectangle', 9)
rectangle_method_9

1.1107663440689195

In [477]:
analytical_solution_9 - rectangle_method_9

-4.5609529327972353e-05

In [478]:
trapezoid_method_9 = solve_integral(3/4, 1.9, 0.01, 'trapezoid', 9)+solve_integral(1.89, 1.99, 0.0001, 'trapezoid', 9)+solve_integral(1.99, 1.999999999, 0.000000001, 'trapezoid', 9)
trapezoid_method_9

1.1107405343120533

In [479]:
analytical_solution_9 - trapezoid_method_9

-1.9799772461803755e-05

In [480]:
Simpson_method_9 = solve_integral(3/4, 1.9, 0.01, 'Simpson', 9)+solve_integral(1.89, 1.99, 0.0001, 'Simpson', 9)+solve_integral(1.99, 1.9999999999, 0.000000001, 'Simpson', 9)
Simpson_method_9

1.110705946408278

In [481]:
analytical_solution_9 - Simpson_method_9

1.4788131313503428e-05